" .vimrc
" See: http://vimdoc.sourceforge.net/htmldoc/options.html for details

" For vim display multi-byte character support (CJK support, for example):
set fileencodings=ucs-bom,utf-8,cp936,big5,euc-jp,euc-kr,gb18030,latin1

" For output (web browser, for example)
set encoding=utf-8

" Independent folder for backup
if has("win32")
    let $VIMFILES = $VIM.'/vimfiles'
else
	let $VIMFILES = $HOME.'/.vim'
endif

" Visual{

" set font (Uses Monaco on Windows and Inconsolata everywhere else)
if has("gui_running")
    if has("gui_gtk2")
        set guifont=Inconsolata\ 12
    elseif has("gui_win32")
        set guifont=Monaco:h11:cANSI
    endif
endif

" show line number
set number

" highlight syntax
syntax on

" tab weight
set tabstop=4

" auto indent
set shiftwidth=4

" Use the appropriate number of spaces to insert a <Tab>.

set expandtab

" to use colors that look good on a dark background
set background=dark

" color theme
colorscheme darkblue

" full screen
au GUIEnter * simalt ~x

" }
